DRIVER_NUMBER_TO_DRIVER = {
    "55": "Sainz",
    "51": "Fittipaldi",
    "47": "Schumacher",
    "44": "Hamilton",
    "31": "Ocon",
    "27": "Hulkenberg",
    "24": "Guanyu",
    "23": "Albon",
    "22": "Tsunoda",
    "20": "Magnussen",
    "18": "Stroll",
    "16": "Leclerc",
    "14": "Alonso",
    "11": "Perez",
    "10": "Gasly",
    "6": "Latifi",
    "5": "Vettel",
    "4": "Norris",
    "3": "Ricciardo",
    "63": "Russell",
    "77": "Bottas",
    "33": "Verstappen",
    "1": "Verstappen",
}

LAP_DATA_CATEGORIES = [
    "DriverNumber",
    "LapNumber",
    "LapTime",
    "Sector1Time",
    "Sector2Time",
    "Sector3Time",
    "SpeedI1",
    "SpeedI2",
    "SpeedFL",
    "SpeedST",
    "Compound",
    "TyreLife",
    "FreshTyre",
]
TIME_DATA = ["LapTime", "Sector1Time", "Sector2Time", "Sector3Time"]

TRAINING_SESSIONS = ["FP1", "FP2", "FP3"]
GP_LIST = [
    "Bahrain",
    "Saudi-Arabian",
    "Abu Dhabi",
    "Portuguese",
    "Spanish",
    "Monaco",
    "Azerbaijan",
    "French",
    "Styrian",
    "Austrian",
    "British",
    "Hungarian",
    "Belgian",
    "Dutch",
    "Italian",
    "Russian",
    "Turkish",
    "United States",
    "Mexican",
    "Brazilian",
]
